import type { NextPage } from 'next';
import Head from 'next/head';
import Button from '../components/atoms/button';
import { Color, Size } from '../enums';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.gradient}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} custom-container`}>
        <h1 className={`${styles.title} col-sm-10 col-md-11 col-lg-10`}>
          Looking for awesome marketing?
        </h1>
        <h2 className={`${styles.subtitle} col-sm-10 col-xl-9 col-xxl-11`}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ab
          esse culpa expedita nam aut officia quod consectetur corporis mollitia
          quidem totam aliquid error asperiores nihil, maiores dolorum debitis
          enim.
        </h2>
        <Button
          buttonColor={Color.Brick}
          buttonSize={Size.Large}
          buttonType={'button'}
          buttonHref={'https://www.google.com'}
          buttonTarget={'_blank'}
          buttonStyle={'main-cta'}
          buttonText={'Get Quote'}
          buttonFullWidth={false}
          hasShadow={true}
        />
      </main>
    </div>
  );
};

export default Home;
